src/main/java/org/folio/rest/impl/InvoiceStorageImpl.java
src/test/java/org/folio/rest/impl/TestBase.java
src/test/java/org/folio/rest/utils/TestEntities.java
src/test/resources/invoice_line.sample

[MODINVOSTO-4](https://issues.folio.org/browse/MODINVOSTO-4) - Implement Basic CRUD APIs for invoice-lines
As per [MODINVOSTO-4](https://issues.folio.org/browse/MODINVOSTO-4) basic CRUD APIs for invoice-lines should be implemented.
CRUD APIs implemented
Actual schemas version pointed

MODINVOSTO-4 - Implement Basic CRUD APIs for invoice-lines

---

descriptors/ModuleDescriptor-template.json
ramls/invoice-line-number.raml
ramls/invoice.raml
src/main/java/org/folio/rest/impl/InvoiceLineNumberAPI.java
src/main/java/org/folio/rest/impl/InvoiceStorageImpl.java
src/main/java/org/folio/rest/persist/HelperUtils.java
src/test/java/org/folio/rest/impl/InvoiceLineNumberTest.java
src/test/java/org/folio/rest/impl/StorageTestSuite.java
src/test/java/org/folio/rest/impl/TestBase.java

https://issues.folio.org/browse/MODINVOSTO-7
* Create a sequence for each invoice and clean it up once we're done with it - much like what's done for po-lines-numbers in mod-orders-storage
* When an invoice is created `POST /invoice-storage/invoices`, create a sequence named the UUID of the invoice.
* When `GET /invoice-storage/invoice-line-numbers?invoiceId=XYZ` is called, get the next value from the sequence associated with the specified invoice ID (UUID)
* When an invoice is closed `PUT /invoice-storage/invoices/<id>`, with `status == PAID or CANCELLED`, delete the sequence associated with the invoice
* When an invoice is being deleted, delete the sequence associated with the invoice
* Reuse the sequence_number schema used by the invoice-number API
* Update unit tests
Before merging …

Implement invoice-line-number API

---

descriptors/ModuleDescriptor-template.json

- Fix the master build in Jenkins
- As per guidelines https://dev.folio.org/guidelines/naming-conventions/#interfaces change:
`invoice-storage.invoice` -> `invoice-storage.invoices`
`invoice-storage.invoice-line` -> `invoice-storage.invoice-lines`
This should fix below:
Ideally all of the PRs involved in breaking changes would be merged in the same day …

Update interface name

---

Dockerfile
descriptors/ModuleDescriptor-template.json
pom.xml
ramls/voucher.raml
src/main/java/org/folio/rest/impl/InvoiceStorageImpl.java
src/main/java/org/folio/rest/impl/VoucherStorageImpl.java
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/utils/TestEntities.java
src/test/resources/voucher.sample

https://issues.folio.org/browse/MODINVOSTO-8- Add the basic implementation for vouchers
1) Add new RAML file
2) add entry to TestEntities to run tests in existing CRUDtest
3) modified the DockerFile to use the alpine image(see https://issues.folio.org/browse/FOLIO-1544)
Ideally all of the PRs involved in breaking changes would be merged in the same day …

MODINVSTO-8- Implement basic CRUD for Vouchers

---

descriptors/ModuleDescriptor-template.json
ramls/voucher.raml
src/main/java/org/folio/rest/impl/VoucherStorageImpl.java
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/utils/TestEntities.java
src/test/resources/voucher_line.sample

https://issues.folio.org/browse/MODINVOSTO-11- Implement basic CRUD for voucher-lines
Added permissions
Added basic implementation for voucher lines
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …

MODINVSTO-11-Implement basic CRUD for voucher-lines

---

descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/MODINVOSTO-11- Correcting the path in interface

MODINVSTOR-11- Path correction

---

descriptors/ModuleDescriptor-template.json
ramls/voucher-number.raml
src/main/java/org/folio/rest/impl/VoucherNumberImpl.java
src/main/resources/templates/db_scripts/schema.json
src/main/resources/templates/db_scripts/voucher_number_sequence.sql
src/test/java/org/folio/rest/impl/InvoiceNumberTest.java
src/test/java/org/folio/rest/impl/StorageTestSuite.java
src/test/java/org/folio/rest/impl/VoucherNumberTest.java

[MODINVOSTO-12](https://issues.folio.org/browse/MODINVOSTO-12) - Implement GET /voucher-storage/voucher-number
Generation sequential voucher numbers is needed.
Create a sequence in the tenantAPI (when the module is enabled for a tenant) - start at 0 (can be changed later on via another API) and return the next value in the sequence when the GET /voucher-storage/voucher-number endpoint is called.

MODINVOSTO-12 - Implement GET /voucher-storage/voucher-number

---

descriptors/ModuleDescriptor-template.json
ramls/voucher-number.raml
src/main/java/org/folio/rest/impl/VoucherNumberImpl.java
src/main/resources/templates/db_scripts/voucher_number_sequence.sql
src/test/java/org/folio/rest/impl/VoucherNumberTest.java

[MODINVOSTO-13](https://issues.folio.org/browse/MODINVOSTO-13) - POST /voucher-storage/voucher-number/start/<value>
One need to implement the ability to allow the tenant to specify the starting value of the voucher number sequence.
Changing voucher number sequence via ALTER SEQUENCE.

MODINVOSTO-13 - Implement POST /voucher-storage/voucher-number/start/<value>

---

src/main/resources/data/invoice-lines/test_invoice_line.json
src/main/resources/data/invoices/test_invoice.json

[MODINVOICE-53](https://issues.folio.org/browse/MODINVOICE-53) - Adjustment schema changes
Pointing to latest schemas
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

MODINVOICE-53 Adjustments schema updates

---

pom.xml
src/main/java/org/folio/rest/impl/InvoiceStorageImpl.java
src/test/java/org/folio/rest/impl/CrudTest.java
src/test/java/org/folio/rest/impl/InvoiceTest.java
src/test/java/org/folio/rest/impl/StorageTestSuite.java

https://issues.folio.org/browse/MODINVOSTO-19
* Implemented logic to remove associated invoice-lines when removing an invoice
* Added unit test
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …

MODINVOSTO-19 Remove associated invoice-lines when removing an invoice

---

src/main/resources/data/invoice-lines/test_invoice_line.json

[MODINVOICE-67](https://issues.folio.org/browse/MODINVOICE-67) Make product id type to be uuid
- Pointing to updated schemas
- updating mock data file

MODINVOICE-67 Make product id type to be uuid

---

src/main/resources/data/invoice-lines/123invoicenumber45-2_release_encumbrance.json
src/main/resources/data/invoices/123invoicenumber45_approved_for_2_orders.json

[MODINVOSTO-25](https://issues.folio.org/browse/MODINVOSTO-25) Improve order-invoice sample data  …

MODINVOSTO-25 Improve order-invoice sample data

---

NEWS.md
pom.xml

[MODINVOSTO-33](https://issues.folio.org/browse/MODINVOSTO-33) Create MODINVOSTO release
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …

MODINVOSTO-33 - Release 1.0.0

---

descriptors/ModuleDescriptor-template.json
ramls/acquisitions-unit-assignments.raml
src/main/java/org/folio/rest/impl/AcquisitionsUnitAssignmentAPI.java
src/main/java/org/folio/rest/impl/TenantReferenceAPI.java
src/main/resources/data/voucher-acquisitions-unit-assignments/AUA-5c499700.json
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/impl/EntitiesCrudTest.java
src/test/java/org/folio/rest/utils/TestEntities.java

https://issues.folio.org/browse/MODINVOSTO-29
Remove the APIs from:
- RAML
- ModuleDescriptor
- Code
- Unit tests are updated
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …

MODINVOSTO-29: Clean-up Implement basic CRUD for /voucher-storage/acquisitions-unit-assignments

---

pom.xml

[MODINVOSTO-28](https://issues.folio.org/browse/MODINVOSTO-28)
[MODINVOSTO-31](https://issues.folio.org/browse/MODINVOSTO-31)
Support querying for invoiceLines and voucherLines based on acquisitions units.
Updating RMB to 26.3.1 to enable [cross table querying](https://github.com/folio-org/raml-module-builder/tree/v26.3.1#cql2pgjson-cross-index-searches)
This option makes it possible to search for invoice(voucher) lines across all invoice(voucher) fields.
Query example: `/voucher-storage/voucher-lines?query=vouchers.acqUnitIds=d1357f1a-e36d-5910-a88c-d84d76bf5217`
**NOTE:** Although the documentation says that the prefix is the name of the table in Camel Case, in practice the name of the table in the prefix must match the one declared in db_scripts/schema.json.
Request with alternative …

MODINVOSTO-28/MODINVOSTO-31 Cross table searches

---

src/main/java/org/folio/rest/impl/InvoiceStorageImpl.java

https://issues.folio.org/browse/MODINVOSTO-38
* Specified database connection used within a transaction.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

MODINVOSTO-38 fixed invoice deletion flow

---

src/main/java/org/folio/rest/impl/InvoiceStorageImpl.java

https://issues.folio.org/browse/MODINVOSTO-38
* fixed pgClient connection handling
While …

MODINVOSTO-38 fixed connection usage

---

descriptors/ModuleDescriptor-template.json
pom.xml
ramls/invoice.raml
ramls/voucher.raml
src/main/resources/data/invoice-lines/10411-1_released_encumbrance.json
src/main/resources/data/invoice-lines/12345-1_released_encumbrance.json
src/main/resources/data/invoice-lines/123invoicenumber45-1.json
src/main/resources/data/invoice-lines/123invoicenumber45-2_release_encumbrance.json
src/main/resources/data/invoice-lines/123invoicenumber57-1.json
src/main/resources/data/invoice-lines/19284-1.json
src/main/resources/data/invoice-lines/30121-1.json
src/main/resources/data/invoice-lines/45723-1_canceled.json
src/main/resources/data/invoice-lines/82912-1.json
src/main/resources/data/invoices/12345_paid.json
src/main/resources/data/voucher-lines/test_voucher_line.json
src/main/resources/templates/db_scripts/data-migration/invoice_lines_table.sql
src/main/resources/templates/db_scripts/data-migration/voucher_lines_table.sql
src/main/resources/templates/db_scripts/schema.json

[MODINVOSTO-41](https://issues.folio.org/browse/MODINVOSTO-41) Allow fund distributions to be specified as amount or percentage
- Updating acq-models and samples
- Adding data migration scripts for `invoice_lines` and `voucher_lines` tables. The same approach is used as in https://github.com/folio-org/mod-orders-storage/pull/157
- Update to RMB `v27.1.1`
- Activate new version of the module
- Make sure old version is enabled
- Check existing invoice and voicher lines
- Enable new module's version with `loadSample=false`
- Make sure new version is enabled
- Check invoice and voicher lines again
If …

MODINVOSTO-41 Allow fund distributions to be specified as amount or percentage

---

src/main/resources/data/invoice-lines/81-1.json
src/main/resources/data/invoices/81_open.json

https://issues.folio.org/browse/MODINVOICE-116
* pointed acq-models to the latest commit
* sample data adjusted
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

MODINVOICE-116 Update purchase order number pattern

---

pom.xml
src/main/java/org/folio/rest/impl/InvoiceLineNumberAPI.java
src/main/java/org/folio/rest/impl/InvoiceStorageImpl.java
src/test/java/org/folio/rest/impl/InvoiceLineNumberTest.java

https://issues.folio.org/browse/MODINVOSTO-45
- Follow https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-271
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …

MODINVSTO-45: upgrading RMB to 29

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/resources/templates/db_scripts/schema.json

MODINVOSTO-20 - Release 3.0.0
invoice-storage.invoice-lines interface version was already updated to 2.0
voucher-storage.voucher-lines interface version was already updated to 2.0
Updating invoice-storage.invoices from 3.0 to 3.1. There was one minor schema change since the last time the version was increased.
Ideally all of the PRs involved in breaking …

MODINVOSTO-20 - Release 3.0.0

---

src/main/resources/templates/db_scripts/schema.json

MODINVOSTO-42 Remove outdated indexes on jsonb->>'foreginKeyId' field
Update schema.json per https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-271

MODINVOSTO-42 Remove outdated indexes on jsonb->>'foreginKeyId' field

---

src/main/resources/templates/db_scripts/schema.json

[MODINVOSTO-55](https://issues.folio.org/browse/MODINVOSTO-55) - Unique Index not being dropped
The unique index on voucher number was set to delete but the fromModuleVersion was not updated. 
fromModuleVersion changed to 'mod-invoice-storage-3.0.1'
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

MODINVOSTO-55 - Unique Index not being dropped

---

descriptors/ModuleDescriptor-template.json
ramls/batch-group.raml
src/main/java/org/folio/rest/impl/BatchGroupImpl.java
src/main/java/org/folio/rest/impl/TenantReferenceAPI.java
src/main/resources/data/batch-groups/test-batch-group.json
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/impl/EntitiesCrudTest.java
src/test/java/org/folio/rest/impl/StorageTestSuite.java
src/test/java/org/folio/rest/impl/SystemDataLoadingTest.java
src/test/java/org/folio/rest/impl/TenantSampleDataTest.java
src/test/java/org/folio/rest/utils/TestEntities.java

[MODINVOSTO-50](https://issues.folio.org/browse/MODINVOSTO-50) - Create batch-group CRUD API
Define and implement the batch-group CRUD API
The batch-group CRUD API defined
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

MODINVOSTO-50 - Create batch-group CRUD API

---

descriptors/ModuleDescriptor-template.json
pom.xml
ramls/batch-voucher-exports.raml
src/main/java/org/folio/rest/impl/BatchVoucherExportsImpl.java
src/main/resources/data/batch-voucher-exports/batch-vouchers/test-batch-voucher.json
src/main/resources/data/batch-voucher-exports/test-batch-voucher-export.json
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/impl/EntitiesCrudTest.java
src/test/java/org/folio/rest/impl/SystemDataLoadingTest.java
src/test/java/org/folio/rest/impl/TenantSampleDataTest.java
src/test/java/org/folio/rest/utils/TestEntities.java

[MODINVOSTO-54](https://issues.folio.org/browse/MODINVOSTO-54) Batch voucher export collection
Define and implement the batch-voucher-exports CRUD API for storage
- Create new RAML
- Update acq-models
- Update ModuleDescriptor
- Implement API code
- Update Unit tests and add test/mock data as needed
- As writing of crud unit test for batch voucher exports require two tables (batch_voucher and batch_group) and batch voucher isn't collection it required to update some related unit tests (`TenantSampleDataTest` and `SystemDataLoadingTest` as not all `TestEntities` are collections)
If there are breaking …

[MODINVOSTO-54] - Create batch-voucher-exports CRUD API

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
ramls/invoice.raml
ramls/voucher.raml
src/main/resources/templates/db_scripts/schema.json

[MODINVOSTO-59](https://issues.folio.org/browse/MODINVOSTO-59) release mod-invoice-storage
new interfaces introduced:
- batch-voucher-storage.export-configurations 1.0
- batch-voucher-storage.batch-vouchers 1.0
- batch-voucher-storage.batch-voucher-exports 1.0
- batch-group-storage.batch-groups 1.0
increased minor version of:
- invoice-storage.invoices 3.1 -> 3.2  (new field batchGroupId in invoice - required, with default value)
- voucher-storage.vouchers 1.1 -> 1.2  (new field batchGroupId in invoice - required, with default value)
If there are breaking changes, please **STOP** and consider the …

MODINVOSTO-59 release 3.1.0

---

NEWS.md
pom.xml

Fix data migration script for batch groups
[MODINVOSTO-62](https://issues.folio.org/browse/MODINVOSTO-62)  - Bugfix Release 3.1.1

[MODINVOSTO-62] - Bugfix Release 3.1.1

---

descriptors/ModuleDescriptor-template.json
ramls/batch-voucher.raml
ramls/invoice.raml
src/main/resources/data/batch-voucher-exports/batch-vouchers/test-batch-voucher.json
src/main/resources/data/batch-vouchers/test-batch-voucher.json
src/main/resources/data/invoice-lines/12345-1_released_encumbrance.json
src/main/resources/data/invoice-lines/123invoicenumber45-1.json
src/main/resources/data/invoice-lines/123invoicenumber45-2_release_encumbrance.json
src/main/resources/data/invoice-lines/123invoicenumber57-1.json
src/main/resources/data/invoice-lines/19284-1.json
src/main/resources/data/invoice-lines/30121-1.json
src/main/resources/data/invoice-lines/81-1.json
src/main/resources/data/invoices/10411_paid.json
src/main/resources/data/invoices/12345_paid.json
src/main/resources/data/invoices/123invoicenumber45_approved_for_2_orders.json
src/main/resources/data/invoices/123invoicenumber57_reviewed.json
src/main/resources/data/invoices/19284_paid.json
src/main/resources/data/invoices/30121_paid.json
src/main/resources/data/invoices/45723_canceled.json
src/main/resources/data/invoices/81_open.json

https://issues.folio.org/browse/MODINVOSTO-58
* sample data updated
* interface versions updated …

MODINVOSTO-58 sample data updated

---

pom.xml
src/main/java/org/folio/rest/impl/ExportConfigurationsImpl.java
src/main/java/org/folio/rest/impl/InitAPIs.java
src/main/java/org/folio/rest/impl/InvoiceNumberImpl.java
src/main/java/org/folio/rest/impl/InvoiceStorageImpl.java
src/main/java/org/folio/rest/impl/VoucherNumberHelper.java
src/main/java/org/folio/rest/impl/VoucherNumberImpl.java
src/main/java/org/folio/rest/persist/Tx.java
src/main/java/org/folio/rest/util/ResponseUtils.java
src/main/java/org/folio/service/BatchVoucherExportsService.java
src/main/java/org/folio/service/BatchVoucherService.java
src/test/java/org/folio/rest/impl/InvoiceLineNumberTest.java
src/test/java/org/folio/rest/impl/InvoiceNumberTest.java
src/test/java/org/folio/rest/impl/VoucherNumberTest.java

[MODINVOSTO-66](https://issues.folio.org/browse/MODINVOSTO-66) - Update to RMB v30.0.1
Update to RMB v30.0.1
RMB and VertX updated
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …

MODINVOSTO-66 - Update to RMB v30.0.1

---

src/main/java/org/folio/rest/impl/TenantReferenceAPI.java
src/test/java/org/folio/rest/impl/TenantSampleDataTest.java

Fix migration
While it's helpful for reviewers to help identify potential problems, …

[MODINVOSTO-67] - Final migration check

---

NEWS.md
pom.xml

[MODINVOSTO-65](https://issues.folio.org/browse/MODINVOSTO-65) …

[MODINVOSTO-65] MODINVOSTO (mod-invoice-storage) release

---

src/test/java/org/folio/rest/impl/DocumentTest.java

https://issues.folio.org/browse/MODINVOICE-172
* pointed acq-models pointed to the latest commit …

MODINVOICE-172 pointed acq-models  to the latest commit

---

NEWS.md
pom.xml
src/main/java/org/folio/rest/impl/TenantReferenceAPI.java
src/main/resources/data/system/batch-groups/FOLIO.json
src/main/resources/templates/db_scripts/batch_groups.sql
src/main/resources/templates/db_scripts/data-migration/voucher_line_fund_code.ftl
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/impl/TenantSampleDataTest.java
src/test/resources/finance_schema.sql

[MODINVOSTO-69](https://issues.folio.org/browse/MODINVOSTO-69)
- cross-module script written
- RMB updated to 30.1.0
- fixed version in pom and news
- removed defoult-system batch group loading via TenantReferenceApi because it causes conflicts when upgrading module and also loaded via sql script
Ideally all of the PRs involved in breaking changes would …

MODINVOSTO-69 Migration script populate "fundDistribution.code" into old voucher lines

---

src/main/resources/templates/db_scripts/schema.json

[MODINVOSTO-72](https://issues.folio.org/browse/MODINVOSTO-72) …

MODINVOSTO-72 Add invoice_line.description fullTextIndex

---

src/main/resources/templates/db_scripts/schema.json

[MODINVOSTO-72](https://issues.folio.org/browse/MODINVOSTO-72)
Fix from version for full test index …

[MODINVOSTO-72] - Fix from version for full search index

---

NEWS.md
pom.xml

[MODINVOSTO-70 - Bugfix release 4.0.1](https://issues.folio.org/browse/MODINVOSTO-70)
- updated NEWS …

[MODINVOSTO-70] - Bugfix release 4.0.1

---

descriptors/ModuleDescriptor-template.json

* https://issues.folio.org/browse/MODINVOSTO-71
* pointed acq-models to the latest commit
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …

MODINVOSTO-71 pointed acq-models to the latest commit

---

Dockerfile
Jenkinsfile
pom.xml
src/main/java/org/folio/rest/impl/InitAPIs.java
src/test/java/org/folio/rest/impl/InvoiceLineNumberTest.java

https://issues.folio.org/browse/MODINVOSTO-80
* updated RMB up to v31.1.0
While it's …

MODINVOSTO-80 updated RMB up to v31.1.0

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

[MODINVOSTO-78](https://issues.folio.org/browse/MODINVOSTO-78) …

MODINVOSTO-78 - Release 4.1.0

---

pom.xml

https://issues.folio.org/browse/MODINVOSTO-90
* fixed logging
* rmb v31.1.4
While it's …

MODINVOSTO-90 fixed logging

---

pom.xml

https://issues.folio.org/browse/MODINVOSTO-93
* RMB 31.1.5 …

MODINVOSTO-93 RMB 31.1.5

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODINVOSTO-91
* updated release notes …

MODINVOSTO-91 release 4.1.1

---

NEWS.md

release 4.1.1  news.md -> master branch

MODINVOSTO-91 news.md

---

descriptors/ModuleDescriptor-template.json
src/main/resources/data/invoices/123invoicenumber45_approved_for_2_orders.json

https://issues.folio.org/browse/MODINVOSTO-96
Update acq-models with Major changes
Major version increased  "invoice-storage.invoices"  from  "4.1" to "5.0"
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …

[MODINVOSTO-96] - increase major version and model change

---

src/main/resources/templates/db_scripts/data-migration/invoice_lock_total_from_boolean_to_number.sql
src/main/resources/templates/db_scripts/schema.json

[MODINVOSTO-97](https://issues.folio.org/browse/MODINVOSTO-97)
- copy `total` value to `lockTotal` if `lockTotal = true`
- delete 'total' and 'subTotal' fields
- delete  `lockTotal` if `lockTotal = false`
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …

MODINVOSTO-97 Write migration script for lock total value

---

descriptors/ModuleDescriptor-template.json
src/main/resources/data/invoice-lines/123invoicenumber45-1.json
src/main/resources/templates/db_scripts/data-migration/reference_number_migration.sql
src/main/resources/templates/db_scripts/schema.json

https://issues.folio.org/browse/MODINVOSTO-81 …

MODINVOSTO-81 Support pair of "refNumber" and "refNumberType" in Invoice line should be an array

---

src/main/resources/data/invoice-lines/123invoicenumber45-1.json

[MODINVOICE-135](https://issues.folio.org/browse/MODINVOICE-135)
Updated resource data to remove the invoice number from invoiceLineNumber
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …

[MODINVOICE-135] Updated resource data to remove the invoice number from invoiceLineNumber

---

src/main/resources/templates/db_scripts/data-migration/copy_enclosureNeeded_and_accountNo_from_invoice.sql
src/main/resources/templates/db_scripts/schema.json

[MODINVOSTO-106](https://issues.folio.org/browse/MODINVOSTO-106)
Updated schema and added a migration script.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

[MODINVOSTO-106] Updated schema and added a migration script

---

NEWS.md
pom.xml

Signed-off-by: Yauheni Kuzmianok <yauheni_kuzmianok@epam.com> …

[MODINVOSTO-99] MODINVOSTO (mod-invoice-storage) release

---

PERSONAL_DATA_DISCLOSURE.md

While it's helpful for reviewers to help identify potential problems, ensuring that it's …

[MODINVOSTO-103] - Add personal data disclosure form

---

src/main/resources/templates/db_scripts/data-migration/populate_vendor_id_to_voucher.sql
src/main/resources/templates/db_scripts/schema.json

https://issues.folio.org/browse/MODINVOSTO-114 …

MODINVOSTO-114 Add vendor data to voucher schema

---

NEWS.md
pom.xml

Bugfix release 5.0.1
While it's helpful for reviewers to help identify potential …

[MODINVOSTO-116] - Bugfix release 5.0.1

---

pom.xml
src/main/java/org/folio/dao/invoice/InvoicePostgresDAO.java
src/main/java/org/folio/rest/impl/ExportConfigurationsImpl.java
src/main/java/org/folio/rest/impl/InitAPIs.java
src/main/java/org/folio/rest/impl/VoucherNumberImpl.java
src/main/java/org/folio/rest/util/ResponseUtils.java
src/main/java/org/folio/service/BatchVoucherExportsService.java
src/main/java/org/folio/service/BatchVoucherService.java
src/main/java/org/folio/service/InvoiceStorageService.java
src/test/java/org/folio/rest/impl/DocumentTest.java
src/test/java/org/folio/rest/impl/EntitiesCrudTest.java
src/test/java/org/folio/rest/impl/ExportConfigCredentialsTest.java
src/test/java/org/folio/rest/impl/InvoiceLineNumberTest.java
src/test/java/org/folio/rest/impl/InvoiceTest.java
src/test/java/org/folio/rest/impl/StorageTestSuite.java
src/test/java/org/folio/rest/impl/SystemDataLoadingTest.java
src/test/java/org/folio/rest/impl/TenantSampleDataTest.java
src/test/java/org/folio/rest/impl/VoucherNumberTest.java
src/test/java/org/folio/rest/utils/IsolatedTenantExtension.java
src/test/java/org/folio/rest/utils/TenantApiTestUtil.java

https://issues.folio.org/browse/MODINVOSTO-109
* update rmb 33.0.0 …

MODINVOSTO-109 rmb 33.0.0

---

NEWS.md
pom.xml

* https://issues.folio.org/browse/MODINVOSTO-108
* updated release note
While it's …

MODINVOSTO-108 release 5.1.0

---

descriptors/ModuleDescriptor-template.json
ramls/voucher-number.raml

https://issues.folio.org/browse/MODINVOSTO-120
Change RAML file with JSON returned format for voucher number API
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

[MODINVOSTO-120] - Master : Cannot set voucher "Starting number" or reset sequence

---

NEWS.md
pom.xml

R2 Bugfix release 5.1.1
While it's helpful for reviewers to help identify potential …

[MODINVOSTO-121] - R2 Bugfix release 5.1.1

---

src/main/resources/templates/db_scripts/data-migration/5.2.0/restriction_for_fund_codes.sql
src/main/resources/templates/db_scripts/schema.json

- MODINVOSTO-122 - Migration script for Fund code in the fund distribution of the order line":" replace with hyphen "-"
- New migration script to convert fund codes.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

[MODINVOSTO-122] Migration for fund codes in fundDistributions

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODINVOSTO-127
* updated release notes
While it's …

MODINVOSTO-127 release 5.2.0 (Kiwi)

---

pom.xml

https://issues.folio.org/browse/MODINVOSTO-134 …

MODINVOSTO-134. Kiwi R3 2021 - Log4j vulnerability verification and correction

---

NEWS.md
pom.xml

KIWI Bugfix 5.2.1
While it's helpful for reviewers to help identify potential problems, …

[MODINVOSTO-137] - KIWI Bugfix 5.2.1

---

pom.xml

https://issues.folio.org/browse/MODINVOSTO-135 …

MODINVOSTO-135. Juniper R2 2021 - Log4j vulnerability verification and correction

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODINVOSTO-136 …

MODINVOSTO-136. Juniper R2 2021 HF #5 module release

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODINVOSTO-139
* Lotus 2022 R1 module release 5.3.0
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …

MODINVOSTO-139 Lotus 2022 R1 module release 5.3.0

---

src/main/resources/templates/db_scripts/schema.json

While it's helpful for reviewers to help identify potential problems, ensuring that it's …

[MODINVOSTO-133]-Added Indexes

---

pom.xml

https://issues.folio.org/browse/MODINVOSTO-145
* updated rmb v 34.1.0 …

MODINVOSTO-145 rmb v34.1.0

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODINVOSTO-142
* update release notes …

MODINVOSTO-142 Morning Glory R2 2022 v5.4.0 release notes

---

pom.xml
src/test/java/org/folio/rest/utils/TenantApiTestUtil.java

https://issues.folio.org/browse/MODINVOSTO-146
*  RMB v35.0.1 upgrade …

MODINVOSTO-146 RMB v35.0.1 upgrade

---

NEWS.md
pom.xml

[MODINVOSTO-149
](https://issues.folio.org/browse/MODINVOSTO-149)
* updated release notes 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …

MODINVOSTO-149 release notes v5.5.0 Nolana R3

---

NEWS.md
src/main/java/org/folio/completablefuture/FolioVertxCompletableFuture.java

https://issues.folio.org/browse/MODINVOSTO-152

[MODINVOSTO-152] Module release Morning Glory R2 2022 Hot Fix #1

---

NEWS.md
pom.xml

especially as the number of inter-module and inter-team dependencies increase.
While it's helpful for reviewers to …

[MODINVOSTO-157] - Release v5.6.0

---

src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/dao/invoice/InvoiceDAO.java
src/main/java/org/folio/dao/invoice/InvoicePostgresDAO.java
src/main/java/org/folio/dao/lines/InvoiceLinesDAO.java
src/main/java/org/folio/dao/lines/InvoiceLinesPostgresDAO.java
src/main/java/org/folio/rest/impl/InvoiceLineNumberAPI.java
src/main/java/org/folio/rest/utils/HelperUtils.java
src/main/java/org/folio/service/InvoiceLineNumberService.java
src/main/java/org/folio/service/InvoiceStorageService.java
src/main/resources/templates/db_scripts/data-migration/5.7.0/replace_invoice_sequences.ftl
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/impl/InvoiceLineNumberTest.java
src/test/java/org/folio/rest/impl/TestBase.java

[MODINVOSTO-162](https://issues.folio.org/browse/MODINVOSTO-162) - Jumps in invoice line numbers
- Removed existing sequence-based implementation
- Replaced by using the new `nextInvoiceLineNumber` field in invoices
- Created a new service for invoice line numbers
- Added a way to create `nextInvoiceLineNumber` based on the invoice lines if it is not defined
- Created new `InvoiceLineDAO` to read invoice lines
- Added a migration script
- Updated unit tests
This needs to be reviewed and merged together with the related PRs in [mod-invoice](https://github.com/folio-org/mod-invoice/pull/412) and [mod-orders](https://github.com/folio-org/mod-orders/pull/750).
- Does this PR meet or exceed the expected …

[MODINVOSTO-162] Create invoice line numbers based on new invoice field

---

Dockerfile
Jenkinsfile
pom.xml
src/main/java/org/folio/rest/utils/ResponseUtils.java
src/main/java/org/folio/service/util/CommonServiceUtil.java

https://issues.folio.org/browse/MODINVOSTO-166
Updated to Java 17 by using these references
https://wiki.folio.org/display/TC/JDK+17+and+Java+17
https://github.com/folio-org/mod-orders/pull/760/files
https://github.com/folio-org/mod-finance-storage/pull/363/files
Ideally, all the PRs involved in …

[MODINVOSTO-166] - Update to Java 17 mod-invoice-storage

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODINVOSTO-170
especially as the number of inter-module and inter-team dependencies …

[MODINVOSTO-170] - Release v5.7.0

---

pom.xml

https://issues.folio.org/browse/MODINVOSTO-171
especially as the number of inter-module and inter-team dependencies …

[MODINVOSTO-171] - Update RMB and vertx to the latest version

---

pom.xml
src/test/java/org/folio/rest/core/RestClientTest.java

https://folio-org.atlassian.net/browse/MODINVOSTO-175
Inspired by: https://github.com/folio-org/raml-module-builder/pull/1146

[MODINVOSTO-175] Upgrade RAML Module Builder

---

pom.xml

Upgrade to the latest folio-di-support
https://github.com/folio-org/folio-di-support/releases/tag/v2.1.0
Release notes: https://github.com/folio-org/folio-di-support/blob/v2.1.0/doc/RELEASE_NOTES.md

MODINVOSTO-175. Upgrade folio-di-support

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/MODINVOSTO-178
especially as the number of inter-module and inter-team …

[MODINVOSTO-178] - Release v5.8.0

---

NEWS.md
pom.xml

especially as the number of inter-module and inter-team dependencies increase.
While it's helpful for reviewers to …

Bug Fix Release v5.8.1

---

src/main/resources/templates/db_scripts/invoice_line_table.sql
src/main/resources/templates/db_scripts/invoices_table.sql
src/main/resources/templates/db_scripts/schema.json

- Add extra search and sorting indexes
- Add 1 RMB-generated invoices index
- Add 5 RMB-generated invoice_lines indexes 
- Add 1 custom invoices index
- Add 4 custom sort invoice_lines indexes 
- Add custom script to schema.json

[MODINV-PTF-OPT]. Add extra search and sorting indexes

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/FOLIO-4102
especially as the number of inter-module and inter-team …

[FOLIO-4102] - Release v5.9.0

---

src/main/java/org/folio/rest/impl/VoucherNumberImpl.java
src/test/java/org/folio/rest/impl/VoucherNumberTest.java

https://folio-org.atlassian.net/browse/MODINVOICE-569
- Fixed sql command by adding sequence owner because of having different sequences in each tenant
- enabled test

[MODINVOICE - 569] - Fix get voucher_sequence sql by setting sequence owner

---

src/main/java/org/folio/rest/impl/VoucherNumberImpl.java

https://folio-org.atlassian.net/browse/MODINVOSTO-194
especially as the number of inter-module and inter-team …

[MODINVOSTO-104] - Fix VoucherNumber query issue

---

Dockerfile
Jenkinsfile
README.md
pom.xml

[[FOLIO-4210] Update to mod-invoice-storage Java 21](https://folio-org.atlassian.net/browse/FOLIO-4210)
Update java and dependency versions

[FOLIO-4210] Update to mod-invoice-storage Java 21

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/MODINVOSTO-196
especially as the number of inter-module and inter-team …

Release v6.0.0

---

src/main/java/org/folio/models/exception/ErrorCodes.java

Remove unused error code after changes made in this PR https://github.com/folio-org/mod-orders/pull/1115/files
for story https://folio-org.atlassian.net/browse/MODORDERS-1265

MODORDERS-1265. Remove ISBN validation/normalization logic

---

descriptors/ModuleDescriptor-template.json
ramls/adjustment_preset.raml
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/rest/impl/AdjustmentPresetsAPI.java
src/main/java/org/folio/rest/impl/InvoiceSettingsAPI.java
src/main/java/org/folio/service/adjustment/AdjustmentPresetsService.java
src/main/java/org/folio/service/setting/SettingsService.java
src/main/resources/templates/db_scripts/data-migration/6.1.0/migrate_configuration_data_to_settings.ftl
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/impl/EntitiesCrudTest.java
src/test/java/org/folio/rest/utils/TestData.java
src/test/java/org/folio/rest/utils/TestEntities.java
src/test/resources/mockdata/adjustment-presets/9d07cef9-9c9a-48f9-ac33-6cff4f23b160.json

[[MODINVOSTO-202] Create Api for storing Invoice adjustments](https://folio-org.atlassian.net/browse/MODINVOSTO-202)
- Create new table for adjustments presets
- Add API implementation for CRUD operations on the new table
- Update tests to cover new API
---

[MODINVOSTO-202] Create Api for storing Invoice adjustments
